# Generated by Django 4.2.5 on 2024-01-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='image',
            field=models.FileField(default=None, max_length=330, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='user2',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
